### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by 3stacks** [stak-digital/units#2]
## Temperature Category

- [ ] Kelvin to Celsius
- [ ] Kelvin to Fahrenheit
- [ ] Celsius to Kelvin
- [ ] Celsius to Fahrenheit
- [ ] Fahrenheit to Kelvin
- [ ] Fahrenheit to Celsius

## Computer Data
